# version: '3.8'
# services:
#   auth-service:
#     build: ./user_service
#     ports:
#       - "5001:5001"
#     env_file:
#       - ./user_service/.env
#     volumes:
#       - .:/app
#       - /app/node_modules
#     depends_on:
#       - user-db
#   post-service:
#     build: ./post_service
#     ports:
#       - "5002:5002"
#     env_file:
#       - ./post_service/.env
#     volumes:
#       - .:/app
#       - /app/node_modules
#     depends_on:
#       - post-db

#     minio:
#     image: minio/minio:latest
#     container_name: minio
#     command: server /data
#     ports:
#       - "9000:9000"
#       - "9001:9001" 
#     environment:
#       - MINIO_ROOT_USER=rootadmin
#       - MINIO_ROOT_PASSWORD=rootadmin
#     volumes:
#       - minio-data:/data


#   user-db:  # Corrected indentation here
#     image: mongo:latest
#     container_name: user-db
#     ports:
#       - "27017:27017"
#     volumes:
#       - user-data:/data/db
#   post-db:
#     image: mongo:latest
#     container_name: post-db
#     ports:
#       - "27018:27017"
#     volumes:
#       - post-data:/data/db

# volumes:
#   user-data:  # Ensure consistency in volume name (used `-` instead of `_`)
#   post-data:  # Ensure consistency in volume name (used `-` instead of `_`)
#   minio-data:

version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    depends_on:
      - auth-service
      - post-service
      - notification-service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


  auth-service:
    build: ./user_service
    ports:
      - "5001:5001"
    env_file:
      - ./user_service/.env
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    depends_on:
      - user-db

  post-service:
    build: ./post_service
    ports:
      - "5002:5002"
    env_file:
      - ./post_service/.env
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    depends_on:
      - post-db
      - notification-service
      - minio
  notification-service:
    build: ./notification_service
    ports:
      - "5003:5003"
    env_file:
      - ./notification_service/.env
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    depends_on:
      - notification-db

  minio:
    image: minio/minio:latest
    # container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    # environment:
    #   - MINIO_ROOT_USER=minioadmin
    #   - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data

  user-db:
    image: mongo:latest
    # container_name: user-db
    ports:
      - "27017:27017"
    volumes:
      - user-data:/data/db

  post-db:
    image: mongo:latest
    # container_name: post-db
    ports:
      - "27018:27017"
    volumes:
      - post-data:/data/db
  notification-db:
    image: mongo:latest
    # container_name: notification-db
    ports:
      - "27019:27017"
    volumes:
      - notification-data:/data/db

volumes:
  user-data:
  post-data:
  notification-data:
  minio-data:
